spring:
  cloud:
    gateway:
      routes:
        - id: viajes-hoteles
          uri: lb://viajes-hoteles
          predicates:
            - Path=/hoteles/**
          filters:
            - StripPrefix=1
        - id: viajes-vuelos
          uri: lb://viajes-vuelos
          predicates:
            - Path=/vuelos/**
          filters:
            - StripPrefix=1
        - id: viajes-reservas
          uri: lb://viajes-reservas
          predicates:
            - Path=/reservas/**
          filters:
            - name: JwtAuthFilter
server:
  port: 9000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
