spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
server:
  port: 9000
jwt:
  prefix: Bearer
  secret: mi-clave-secreta-super-segura
logging:
  level:
    org.springframework.security: TRACE
    org.springframework.web: TRACE
    org.springframework.boot: TRACE
