spring:
  cloud:
    gateway:
      routes:
        - id: viajes-hoteles
          uri: lb://viajes-hoteles
          predicates:
            - Path=/hoteles/**
          filters:
            - StripPrefix=1
        - id: viajes-vuelos
          uri: lb://viajes-vuelos
          predicates:
            - Path=/vuelos/**
          filters:
            - StripPrefix=1
        - id: viajes-reservas
          uri: lb://viajes-reservas
          predicates:
            - Path=/reservas/**
          filters:
            - name: JwtAuthenticationFilter
    discovery:
      client:
        service-id: viajes-eureka
        enabled: true
      locator:
        enabled: true
        lower-case-service-id: true
server:
  port: 9000
